### ISSUE TITLE
Join the org

### ISSUE THREAD

**Issue by VasudevJaiswal** [amino19/amino19#1]
[Click Here](https://github.com/Jaidevstudio)

**Comment by aminoxix** [comment]
> [Click Here](https://github.com/Jaidevstudio)

@VasudevJaiswal: Definitely! Shall I know more about your organization?

BTW, I too leading an organization as [**DEVSTRONS'**](https://linktr.ee/devstrons) :slightly_smiling_face:

**Comment by VasudevJaiswal** [comment]
Check your Email or org Page [Click here](https://github.com/jaidevstudio)

**Comment by ghost** [comment]
Hi @VasudevJaiswal , it's really great to see this community :)
and thanks for sharing it with us!
but actually, it's not the right place and way to share!
we will surely check it out, but for now I request @amino19 to close this issue

**Comment by VasudevJaiswal** [comment]
> Hi @VasudevJaiswal , it's really great to see this community :)
> and thanks for sharing it with us!
> but actually, it's not the right place and way to share!
> we will surely check it out, but fir now I request @amino19 to close this issue

@PulkitSinghDev 
1.  Plz check email or visit page [CLICK HERE](https://github.com/jaidevstudio)
